name: New Skill Proposal
description: Propose a new marketing or ad-tech skill
title: "[Skill]: "
labels: ["new-skill"]
body:
  - type: input
    id: use_case
    attributes:
      label: Use case
      placeholder: What repeated workflow does this skill solve?
  - type: textarea
    id: inputs
    attributes:
      label: Required inputs
  - type: textarea
    id: risks
    attributes:
      label: Risks and guardrails
